package labels

const (
	CEX          LabelName = "CEX"
	CEX_BINANCE  LabelName = "CEX_BINANCE"
	CEX_OKX      LabelName = "CEX_OKX"
	CEX_COINBASE LabelName = "CEX_COINBASE"
	CEX_KRAKEN   LabelName = "CEX_KRAKEN"
	CEX_BITGET   LabelName = "CEX_BITGET"
	CEX_GATEIO   LabelName = "CEX_GATEIO"
	CEX_BYBIT    LabelName = "CEX_BYBIT"
	CEX_KUCOIN   LabelName = "CEX_KUCOIN"
	CEX_HUOBI    LabelName = "CEX_HUOBI"
	CEX_MEXC     LabelName = "CEX_MEXC"
	CEX_FTX      LabelName = "CEX_FTX"
	CEX_BITFINEX LabelName = "CEX_BITFINEX"
	CEX_BITMEX   LabelName = "CEX_BITMEX"
	CEX_BITSTAMP LabelName = "CEX_BITSTAMP"

	CEX_HOT_WALLET LabelName = "CEX_HOT_WALLET"
)

// cex names
const (
	CEX_ID LabelID = iota + 20000
	CEX_BINANCE_ID
	CEX_OKX_ID
	CEX_COINBASE_ID
	CEX_KRAKEN_ID
	CEX_BITGET_ID
	CEX_GATEIO_ID
	CEX_BYBIT_ID
	CEX_KUCOIN_ID
	CEX_HUOBI_ID
	CEX_MEXC_ID
	CEX_FTX_ID
	CEX_BITFINEX_ID
	CEX_BITMEX_ID
	CEX_BITSTAMP_ID
)

// cex others
const (
	CEX_HOT_WALLET_ID LabelID = iota + 21000
)
