package labels

const (
	CHAIN_BITCOIN  LabelName = "CHAIN_BITCOIN"
	CHAIN_ETHEREUM LabelName = "CHAIN_ETHEREUM"
	CHAIN_SOLANA   LabelName = "CHAIN_SOLANA"
	CHAIN_BASE     LabelName = "CHAIN_BASE"
	CHAIN_ARBITRUM LabelName = "CHAIN_ARBITRUM"
	CHAIN_OPTIMISM LabelName = "CHAIN_OPTIMISM"
)

const (
	CHAIN_BITCOIN_ID LabelID = iota + 1
	CHAIN_ETHEREUM_ID
	CHAIN_SOLANA_ID
	CHAIN_BASE_ID
	CHAIN_ARBITRUM_ID
	CHAIN_OPTIMISM_ID
)
