package labels

const (
	CHAIN_BITCOIN  Label = "CHAIN_BITCOIN"
	CHAIN_ETHEREUM Label = "CHAIN_ETHEREUM"
	CHAIN_SOLANA   Label = "CHAIN_SOLANA"
	CHAIN_BASE     Label = "CHAIN_BASE"
	CHAIN_ARBITRUM Label = "CHAIN_ARBITRUM"
	CHAIN_OPTIMISM Label = "CHAIN_OPTIMISM"

	SOL_STAKE                     Label = "SOL_STAKE"
	SOL_STAKING                   Label = "SOL_STAKING"
	SOL_STAKING_VOTE              Label = "SOL_STAKING_VOTE"
	SOL_STAKING_STAKE_NET_ADDRESS Label = "SOL_STAKING_STAKE_NET_ADDRESS"
	SOL_ON_CURVE                  Label = "SOL_ON_CURVE"
	SOL_OFF_CURVE                 Label = "SOL_OFF_CURVE"
	SOL_PROGRAM                   Label = "SOL_PROGRAM"
)
