package labels

const (
	DEX          Label = "DEX"
	DEX_UNISWAP  Label = "DEX_UNISWAP"
	DEX_OPENSEA  Label = "DEX_OPENSEA"
	DEX_ONEINCH  Label = "DEX_ONEINCH"
	DEX_JUPITER  Label = "DEX_JUPITER"
	DEX_RAYDIUM  Label = "DEX_RAYDIUM"
	DEX_ORCA     Label = "DEX_ORCA"
	DEX_LIFINITY Label = "DEX_LIFINITY"
	DEX_METEORA  Label = "DEX_METEORA"
	DEX_PUMPFUN  Label = "DEX_PUMPFUN"
	DEX_PHOENIX  Label = "DEX_PHOENIX"
	DEX_APEPRO   Label = "DEX_APEPRO"
	DEX_FLUXBEAM Label = "DEX_FLUXBEAM"
	DEX_SANCTUM  Label = "DEX_SANCTUM"
	DEX_OPENBOOK Label = "DEX_OPENBOOK"

	DEFI_KAMINO Label = "DEFI_KAMINO"
)
