package labels

const (
	DEX          LabelName = "DEX"
	DEX_UNISWAP  LabelName = "DEX_UNISWAP"
	DEX_OPENSEA  LabelName = "DEX_OPENSEA"
	DEX_ONEINCH  LabelName = "DEX_ONEINCH"
	DEX_JUPITER  LabelName = "DEX_JUPITER"
	DEX_RAYDIUM  LabelName = "DEX_RAYDIUM"
	DEX_ORCA     LabelName = "DEX_ORCA"
	DEX_LIFINITY LabelName = "DEX_LIFINITY"
	DEX_METEORA  LabelName = "DEX_METEORA"
	DEX_PUMPFUN  LabelName = "DEX_PUMPFUN"
	DEX_PHOENIX  LabelName = "DEX_PHOENIX"
	DEX_APEPRO   LabelName = "DEX_APEPRO"
	DEX_FLUXBEAM LabelName = "DEX_FLUXBEAM"
	DEX_SANCTUM  LabelName = "DEX_SANCTUM"
	DEX_OPENBOOK LabelName = "DEX_OPENBOOK"
)

const (
	DEX_ID LabelID = iota + 10000
	DEX_UNISWAP_ID
	DEX_OPENSEA_ID
	DEX_ONEINCH_ID
	DEX_JUPITER_ID
	DEX_RAYDIUM_ID
	DEX_ORCA_ID
	DEX_LIFINITY_ID
	DEX_METEORA_ID
	DEX_PUMPFUN_ID
	DEX_PHOENIX_ID
	DEX_APEPRO_ID
	DEX_FLUXBEAM_ID
	DEX_SANCTUM_ID
	DEX_OPENBOOK_ID
)
